### ISSUE TITLE
novelai加载后会导致其它插件加载失败

### ISSUE THREAD

**Issue by zhulinyv** [sena-nana/nonebot-plugin-novelai#10]
![image](https://user-images.githubusercontent.com/66541860/197331811-26921a8d-013c-45d9-835f-4bddcbd24ff4.png)
![image](https://user-images.githubusercontent.com/66541860/197331814-ac27fa00-41e1-4c1c-854b-b37ca6703f3a.png)
![image](https://user-images.githubusercontent.com/66541860/197331824-ca6d9c53-f75c-4200-a8f7-6018a20a8649.png)
如图，其它插件加载会出现 RuntimeError: There is no current event loop in thread 'MainThread'.  错误。

我尝试将其它插件中的
`loop = asyncio.get_event_loop()`
改为
`
loop =  asyncio.new_event_loop()
asyncio.set_event_loop(loop)
`
可是问题依旧。 T _ T

**Comment by sena-nana** [comment]
将在今晚的版本中修复
