### ISSUE TITLE
无法使用，报错

### ISSUE THREAD

**Issue by AHBYCR** [sena-nana/nonebot-plugin-novelai#13]
我的python版本是3.8.10
![image](https://user-images.githubusercontent.com/96919094/206862662-5dae7c70-626c-401c-a10f-9d67daf47bc1.png)
![image](https://user-images.githubusercontent.com/96919094/206862688-a2a64ceb-4cbc-4415-827d-9da8bc4e7a15.png)

**Comment by AHBYCR** [comment]
我纯小白，可能有没描述好的地方，见谅

**Comment by sena-nana** [comment]
那就把类型标注去掉就好，就是冒号和后面的list[str]，这个去了不影响运行（没想到3.8居然这个也不支持）
