### ISSUE TITLE
NOVELAI_PURE设置未生效

### ISSUE THREAD

**Issue by hAcKlyc** [sena-nana/nonebot-plugin-novelai#15]
配置参数env里设置了true，但是实际返回的仍然是group转发的形式

NOVELAI_PURE=true

**Comment by hAcKlyc** [comment]
原因找到了。。config里的函数问题
    async def get_value(cls, group_id, arg: str):
这个函数只正常获取self.keys包含的设置，不在这个范围的会返回None

但是逻辑上，这个功能应该是全局config，不限制某个群？这个def get_value的else或者elif里把其他参数加一下哈

**Comment by sena-nana** [comment]
pure属于bot主才能控制的参数，因为涉及到了可能与风控有关的bot行为，不在管理插件的控制范围内
