### ISSUE TITLE
点数不足

### ISSUE THREAD

**Issue by ghost** [sena-nana/nonebot-plugin-novelai#17]
novelai_paid = 2 还是提示点数不足
![48 2V550HYB$WO)XRZ%52AE](https://user-images.githubusercontent.com/118903437/208821100-4555c3be-eedd-4075-87cf-52eb1c5bb561.png)

**Comment by sena-nana** [comment]
手动去config.py里改成3，这个issue和已有的重复了

**Comment by ghost** [comment]
原来如此，解决了，多谢
