### ISSUE TITLE
请问有没有白名单功能

### ISSUE THREAD

**Issue by QwindF** [sena-nana/nonebot-plugin-novelai#18]
请问有没有白名单功能，我怕我号寄了

**Comment by QwindF** [comment]
还有，有些指令无法正常使用？
![image](https://user-images.githubusercontent.com/87116340/209462437-2603ed00-9557-497a-98d0-5b7395a514c2.png)

**Comment by sena-nana** [comment]
配置里on改成false，然后用aidraw on就行

**Comment by QwindF** [comment]
哪里的配置env的吗？

**Comment by QwindF** [comment]
> 还有，有些指令无法正常使用？ ![image](https://user-images.githubusercontent.com/87116340/209462437-2603ed00-9557-497a-98d0-5b7395a514c2.png)
原因找到了
![_8`Z~Z$}(P5{$5IZNCS~(68](https://user-images.githubusercontent.com/87116340/209463363-552e7158-66d3-4c38-bceb-427faf6b00ad.png)

你的文档是没写完吗？

**Comment by sena-nana** [comment]
env，还有关于使用的问题尽量加群问

**Comment by sena-nana** [comment]
没写完，0.6补全

**Comment by QwindF** [comment]
我有在群里at你（），行吧qwq,这GitHub不开魔法都上不了了

**Comment by sena-nana** [comment]
我没有看到任何艾特我的消息
