### ISSUE TITLE
没有报错信息，但无法使用

### ISSUE THREAD

**Issue by Amber-siley** [sena-nana/nonebot-plugin-novelai#19]
**安装插件也没有提示有什么缺失**
![image](https://user-images.githubusercontent.com/75154201/209832586-bbe01a43-b1a4-4aa6-99f0-c5fe4d7a1fef.png)

**这是sd的**，发送指令后没有反应
![image](https://user-images.githubusercontent.com/75154201/209831167-940d665b-7868-4914-a0d1-82bbf7a3cfb7.png)

**这是bot的**发送指令以后，只有这一串信息
![image](https://user-images.githubusercontent.com/75154201/209832096-8e5f9136-f773-456c-bb85-8537374216a8.png)

![image](https://user-images.githubusercontent.com/75154201/209831479-758b4122-8a56-42d3-9f84-7918f762f0c5.png)

**这是.env.dev的**端口也没有问题
![image](https://user-images.githubusercontent.com/75154201/209831634-11f76000-558e-4f33-9320-7e6bc383067d.png)

**这是sd的启动文件**
![image](https://user-images.githubusercontent.com/75154201/209832419-5e6a450c-b2f8-406e-9e4d-0568404baf64.png)

**Comment by zhulinyv** [comment]
I have the same problem, but I found there are two possible reasons here.

1.It cannot work in private chats.
2.Maybe your tags contain the wrong arguments, such as `.aidraw loli -p -c 10` , this is wrong. The correct arguments should be this `.aidraw loli -r p -c 10` .

**Comment by sena-nana** [comment]
首先，插件目前还没有支持私聊使用，这一点在其他的issue里已经提到过，并且从直接skip掉来看，最有可能是这种可能。因为这属于重复issue，我先close了，如果是其他原因导致的我再打开
