### ISSUE TITLE
[Bug]: sd生成完成后bot未发送图片

### ISSUE THREAD

**Issue by mangokuma** [sena-nana/nonebot-plugin-novelai#24]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项
- [X] 我已使用最新版本测试过，确认问题依旧存在
- [X] 我确定在 GitHub Issues 中没有相同或相似的问题

### 发生错误的版本号

v0.5.6

### 问题描述

sd生成完成后bot未发送图片

### 如何复现

1. 我在配置文件里设置了……
HOST=127.0.0.1
PORT=8080
LOG_LEVEL=DEBUG
FASTAPI_RELOAD=FALSE

NOVELAI_TOKEN=""
NOVELAI_TAG=""
NOVELAI_PAID=1
NOVELAI_DAYLIMIT=0
NOVELAI_MODE="sd"
NOVELAI_SITE="192.168.50.3:9000"

2. 我的运行环境是……
python 3.10.4

3. 我对BOT使用的指令是……
/aidraw 1 boy

4. 我做的其他操作是……
无其他操作

5. 发生了……
sd生成完成后bot未发送图片

### 日志信息

nb日志
03-16 12:38:37 [SUCCESS] nonebot | ONEBOT V11 21xxxxx61 | [message.group.normal]: Message 457688005 from 25xxxxxx69@[群:83xxxxx43] "/aidraw 1 boy"
03-16 12:38:37 [DEBUG] nonebot | Checking for matchers in priority 1...
03-16 12:38:37 [DEBUG] nonebot | Checking for matchers in priority 4...
03-16 12:38:37 [DEBUG] nonebot | Checking for matchers in priority 5...
03-16 12:38:37 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_novelai.aidraw, type=message, priority=5, temp=False>
03-16 12:38:37 [DEBUG] nonebot | Running matcher <Matcher from nonebot_plugin_novelai.aidraw, type=message, priority=5, temp=False>
03-16 12:38:37 [DEBUG] nonebot | Running handler <Dependent call=<function aidraw_get at 0x000001CAFFE536D0>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='event', type=GroupMessageEvent, required=True), ModelField(name='args', type=Namespace, required=True)], parameterless=[]>
03-16 12:38:37 [DEBUG] nonebot_plugin_novelai | time=2023-03-16 12:38:37;user_id=25xxxxxx69;group_id=83xxxxx43;cost=0;batch=1;seed=[63850860];scale=11;strength=0.7;noise=0.2;sampler=k_euler_ancestral;model=;steps=28;width=512;height=768;img2img=False;tags=masterpiece, best quality,,1 boy ,;ntags=lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, pubic hair,long neck,blurry  ,
03-16 12:38:37 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
03-16 12:38:38 [INFO] nonebot_plugin_novelai | 队列开始
03-16 12:38:38 [DEBUG] nonebot | OneBot V11 | Calling API get_group_member_info
03-16 12:38:38 [INFO] nonebot_plugin_novelai | 队列剩余1人 | 开始生成：time=2023-03-16 12:38:37;user_id=25xxxxxx69;group_id=83xxxxx43;cost=0;batch=1;seed=[63850860];scale=11;strength=0.7;noise=0.2;sampler=k_euler_ancestral;model=;steps=28;width=512;height=768;img2img=False;tags=masterpiece, best quality,,1 boy ,;ntags=lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, pubic hair,long neck,blurry  ,
03-16 12:38:58 [DEBUG] nonebot_plugin_novelai | 获取到返回图片，正在处理
03-16 12:38:58 [INFO] nonebot_plugin_novelai | 队列剩余1人 | 生成完毕：time=2023-03-16 12:38:37;user_id=2510166169;group_id=830019043;cost=0;batch=1;seed=[63850860];scale=11;strength=0.7;noise=0.2;sampler=k_euler_ancestral;model=;steps=28;width=512;height=768;img2img=False;tags=masterpiece, best quality,,1 boy ,;ntags=lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, pubic hair,long neck,blurry  ,
03-16 12:38:58 [DEBUG] nonebot | OneBot V11 | Calling API send_group_forward_msg
03-16 12:38:58 [INFO] nonebot_plugin_novelai | 队列结束
03-16 12:38:58 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_novelai.aidraw, type=message, priority=5, temp=False> running complete
03-16 12:38:58 [DEBUG] nonebot | Stop event propagation

群内截图
![image](https://user-images.githubusercontent.com/47619527/225517713-bf63f4d2-c88b-481d-9ee4-be117d89b50d.png)

sd截图
![image](https://user-images.githubusercontent.com/47619527/225517890-be1463a1-ec92-40bc-a7cf-285427bce519.png)

**Comment by mangokuma** [comment]
sd通过Nginx反向代理访问

**Comment by sena-nana** [comment]
可能是bot被风控，换下pure模式，如果还是不行换个号试试

**Comment by mangokuma** [comment]
用其他模块实现了，暂时不知道原因，先close了。
