### ISSUE TITLE
[Feature]: 增添预设配置

### ISSUE THREAD

**Issue by niucattle** [sena-nana/nonebot-plugin-novelai#26]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项
- [X] 我已使用最新版本测试过，确认功能尚未实现
- [X] 我确定在 GitHub Issues 中没有相同或相似的需求

### 需求原因

我在自己搭建的sd中加入了很多lora模型，这些 lora模型有特定的触发词，比如澄闪是<lora:澄闪7(头巾与耳朵;headband,两套衣服santa coat)(建议):1>而这种打起来非常的不方便，所以希望用中文代替。

### 预期行为

能够方便地生成预期的图片。

### 解决方案

添加一个词条替换功能，比如可以自行配置 德狗/德克萨斯可以直接用来替换 <lora:Omertosa:1>，当然，被替换的可能不只是一个词条，还可能是一组词条，替换词也可能有很多个（很多角色都有外号）。比如上面提到的澄闪lora模型，内置的也有不同服装的触发词，在这种情况下可以用“澄闪皮肤”这一个中文词条来替换”<lora:澄闪7(头巾与耳朵;headband,两套衣服santa coat)(建议):1>,santa coat”这两个词条，触发词也可以替换为"粉毛皮肤"。

**Comment by sena-nana** [comment]
该需求已在路线图中，预计在0.6.x加入

**Comment by niucattle** [comment]
好的！
