### ISSUE TITLE
novelAI插件白嫖服务器的配置问题

### ISSUE THREAD

**Issue by WindraiteLesd** [sena-nana/nonebot-plugin-novelai#7]
白嫖服务器(Colab)的TOKEN,API和SITE都应该如何获取和配置？
这几点是否应当写进readme

**Comment by sena-nana** [comment]
Token应该不需要，api是服务器的域名。site在代码中似乎并未使用。我这边缺少能够测试的服务器，这个功能是其他人的pr中带有的，所以并没有来得及实际测试，readme中也没有细写。明天我会尝试连接上自机的服务器。

**Comment by sena-nana** [comment]
Colab是否能够白嫖我不太清楚，这个功能是对接webui和naifu的

**Comment by WindraiteLesd** [comment]
> Colab是否能够白嫖我不太清楚，这个功能是对接webui和naifu的

https://wafuwafu.com/?p=4714
其实就是naifu

**Comment by sena-nana** [comment]
今天会测试一下连接服务器，顺便更新一下版本

**Comment by sena-nana** [comment]
naifu和sd均已经适配完成
