### ISSUE TITLE
novelai可以不可以支持python3.9呀，我在用真寻，不支持3.10

### ISSUE THREAD

**Issue by edwer1** [sena-nana/nonebot-plugin-novelai#8]

**Comment by sena-nana** [comment]
暂时没有这个打算，如果想要使用可以clone源代码然后删除match部分然后直接把原本的参数给input，只有这部分使用了3.10特性。删除后只是无法匹配seed和画幅，对主要功能没有影响。

**Comment by edwer1** [comment]
![image](https://user-images.githubusercontent.com/44490405/195544254-a8dfbb47-6e8d-42c9-b28c-4e9d989abe1e.png)
哥们不怎么会python，这样该怎么改呢

**Comment by sena-nana** [comment]
去看init文件，你多输了东西

**Comment by sena-nana** [comment]
建议百度

**Comment by edwer1** [comment]
哦哦确实是，改完了之后不报错但是调用的话又有这个错误
![image](https://user-images.githubusercontent.com/44490405/195545624-a96e9332-b172-4345-8f55-4a538234f4a7.png)

**Comment by sena-nana** [comment]
你多传了参，这种问题百度就能解决，还有，如果不知道有什么用的话无关的地方不要乱动
